### ISSUE TITLE
CORS Header

### ISSUE THREAD

**Issue by liaocanada** [rynobax/indeed-scraper#4]
Hi, 

I'm trying to use this API, and I'm getting this in the browser console:
No 'Access-Control-Allow-Origin' header is present on the requested resource.

After reading about [CORS](https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present), I'm still not too sure how to handle this error.

Should a CORS header be something I add in my own code, or as something managed within the API? Any help would be appreciated as I am a complete beginner to this. 

Thanks

**Comment by rynobax** [comment]
So tbh I'm not sure I understand CORS after bumping into it a few times.  I *think* that CORS prevents one website from making request to another website, in order to prevent malicious sites.  For example, I couldn't have my personal website make a request to github.com, otherwise if you visited it, I could do evil things like log you out.

If you need to make a request to a server on another domain, you could have the server return a CORS header that essentially says "its ok to allow requests from this domain: baxley.dev", and then chrome would allow it.

In this case, Indeed controls their headers, so it won't be possible to use this library in the browser (CORS is a safety measure implemented by browsers I think).  If you want to use this library, you will need to do it in node.js, which does not worry about CORS.  So if you wanted to have a website that displayed the results, you would have to proxy the requests through your own server.  Basically your website -> your server -> indeed-scraper -> indeed.com.

I hope this helps!

**Comment by RNogales94** [comment]
https://youtu.be/HgdAwvt2vSs

Maybe this helps you to understand that error

**Comment by liaocanada** [comment]
Thanks, I'll have a look.
